### PR TITLE
Initial formulation of as_tibble

### PR DESCRIPTION
**Pull request by aedobbyn**

### CODE REVIEW

**Comment by aedobbyn** [comment]
> I used your your first approach adding classes to the response objects, so that I could make use of the S3 system and its generic functions

Nice, I like this approach!

> Ah, and I named the function owmr_as_tibble because of the already existing as_tibble in the tibble package itself.

Makes sense, that function seems like something we wouldn't want to mask.

My only suggestion at the first pass would be [to use `library` instead of `require`](https://yihui.name/en/2014/07/library-vs-require/) [here](https://github.com/crazycapivara/owmr/blob/develop/docs/index.rmd#L26), but of course this is very minor.

> If this is fine for you, I would like to add you as contributor to the DESCRIPTION file.

Fine by me -- thanks for asking!

Let me know if you'd like me to look through anything else like the [tests](https://travis-ci.org/crazycapivara/owmr/builds/423679482#L1478).

**Comment by crazycapivara** [comment]
I already added tests and updated the README file in develop. For the docs I want to switch to [pkgdown](https://pkgdown.r-lib.org/articles/pkgdown.html). In this step I will replace `require` with `library`.

**Comment by aedobbyn** [comment]
> I already added tests 
Yeah sorry what I linked to up there in was the test errors on Travis. I can look into them if you like.

> For the docs I want to switch to pkgdown. In this step I will replace `require` with `library`.
Sounds great!

**Comment by crazycapivara** [comment]
I managed to merge the new features to master and to switch to [pkgdown-docs](https://crazycapivara.github.io/owmr/).

**Comment by aedobbyn** [comment]
Nice! Let me know if you want me to do any work on the docs.

**Comment by crazycapivara** [comment]
Hi, sorry for the delay in my reply. Thanx a lot for your great input. If you have some suggestions on the docs it is always welcome.

**Pull request closed without merging**
